make:
	mkdir data
	cd src && make
	cd doc && make
	cp ./doc/report.pdf ./report.pdf

run:
	mkdir data
	cd src && make
	cd doc && make
	cp ./doc/report.pdf ./report.pdf

report:
	cd doc && make
	cp ./doc/report.pdf ./report.pdf

story:
	cd doc && make
	cp ./doc/report.pdf ./report.pdf